name: Project3 Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/*.gradle*','**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests (auto-detect)
        run: |
          if [ -f settings.gradle ] || [ -f settings.gradle.kts ] ; then
            if grep -q "include ':app'" settings.gradle 2>/dev/null || grep -q "include(':app')" settings.gradle.kts 2>/dev/null || [ -d "app" ]; then
              ./gradlew :app:testDebugUnitTest --no-daemon --stacktrace
            else
              ./gradlew test --no-daemon --stacktrace
            fi
          else
            if [ -d "app" ]; then
              ./gradlew :app:testDebugUnitTest --no-daemon --stacktrace
            else
              ./gradlew test --no-daemon --stacktrace
            fi
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/test-results
            build/test-results

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests
            build/reports/tests
